<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>imx708_camera_py</name>
  <version>0.1.0</version>
  <description>Arducam IMX708 ROS 2 publisher (Python) for Jetson Orin Nano.</description>
  <maintainer email="you@example.com">your name</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
